name: My First Workflow

# trigger
on: #or [push]. Both are array notations in yaml
- push

# Jobs in the workflow
jobs:
  # job name
  my-first-workflow:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to peform task 
    steps:
      - name: echo the date
        run: echo "The current time and date in GitHub is $(date)"
      - name: echo information about the contex
        run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}"

